# Generated by Django 5.0.7 on 2024-07-22 13:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_alter_project_demo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='425x425px recommended', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=cloudinary.models.CloudinaryField(help_text='425x425px recommended', max_length=255, verbose_name='project_images'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='425x425px recommended', max_length=255, verbose_name='project_images_others'),
        ),
    ]
