# Generated by Django 5.0.7 on 2024-07-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_alter_profile_image_alter_project_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
